Buildroot: /home/mv/build
Prefix: /
Name: xindy-make-rules
Version: 0.2
Release: 2
Summary: A collection of xindy rules
Copyright: Unclear
Distribution: Fedora Core 2
Group: Converted/text
Requires: xindy >= 2.1

%define _rpmdir ../
%define _rpmfilename %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm
%define _unpackaged_files_terminate_build 0

%description
This package contains the following:

A Perl script to transform a description of a (language-specific)
alphabet into a set of sorting rules for xindy. Alphabets for some languages
are also provided.

A Perl script to generate sets of rules which are needed in combination
with the LaTeX `inputenc' package.

The rules generated from that scripts


(Converted from a deb package by alien version 8.46.)



%files
%dir "/usr/"
%dir "/usr/share/"
%dir "/usr/share/xindy/"
%dir "/usr/share/xindy/modules/"
%dir "/usr/share/xindy/modules/lang/"
%dir "/usr/share/xindy/modules/lang/albanian/"
"/usr/share/xindy/modules/lang/albanian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/albanian/utf8.xdy"
"/usr/share/xindy/modules/lang/albanian/latin1-test.xdy"
"/usr/share/xindy/modules/lang/albanian/latin1.xdy"
%dir "/usr/share/xindy/modules/lang/belarusian/"
"/usr/share/xindy/modules/lang/belarusian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/belarusian/utf8.xdy"
"/usr/share/xindy/modules/lang/belarusian/cp1251-test.xdy"
"/usr/share/xindy/modules/lang/belarusian/cp1251.xdy"
"/usr/share/xindy/modules/lang/belarusian/iso88595-test.xdy"
"/usr/share/xindy/modules/lang/belarusian/iso88595.xdy"
"/usr/share/xindy/modules/lang/belarusian/isoir111-test.xdy"
"/usr/share/xindy/modules/lang/belarusian/isoir111.xdy"
%dir "/usr/share/xindy/modules/lang/bulgarian/"
"/usr/share/xindy/modules/lang/bulgarian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/bulgarian/utf8.xdy"
"/usr/share/xindy/modules/lang/bulgarian/cp1251-test.xdy"
"/usr/share/xindy/modules/lang/bulgarian/cp1251.xdy"
"/usr/share/xindy/modules/lang/bulgarian/iso88595-test.xdy"
"/usr/share/xindy/modules/lang/bulgarian/iso88595.xdy"
"/usr/share/xindy/modules/lang/bulgarian/koi8-r-test.xdy"
"/usr/share/xindy/modules/lang/bulgarian/koi8-r.xdy"
%dir "/usr/share/xindy/modules/lang/croatian/"
"/usr/share/xindy/modules/lang/croatian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/croatian/utf8.xdy"
"/usr/share/xindy/modules/lang/croatian/cp1250-test.xdy"
"/usr/share/xindy/modules/lang/croatian/cp1250.xdy"
"/usr/share/xindy/modules/lang/croatian/latin2-test.xdy"
"/usr/share/xindy/modules/lang/croatian/latin2.xdy"
%dir "/usr/share/xindy/modules/lang/czech/"
"/usr/share/xindy/modules/lang/czech/utf8-test.xdy"
"/usr/share/xindy/modules/lang/czech/utf8.xdy"
"/usr/share/xindy/modules/lang/czech/cp1250-test.xdy"
"/usr/share/xindy/modules/lang/czech/cp1250.xdy"
"/usr/share/xindy/modules/lang/czech/latin2-test.xdy"
"/usr/share/xindy/modules/lang/czech/latin2.xdy"
%dir "/usr/share/xindy/modules/lang/danish/"
"/usr/share/xindy/modules/lang/danish/utf8-test.xdy"
"/usr/share/xindy/modules/lang/danish/utf8.xdy"
"/usr/share/xindy/modules/lang/danish/cp1252-test.xdy"
"/usr/share/xindy/modules/lang/danish/cp1252.xdy"
"/usr/share/xindy/modules/lang/danish/latin1-test.xdy"
"/usr/share/xindy/modules/lang/danish/latin1.xdy"
"/usr/share/xindy/modules/lang/danish/latin9-test.xdy"
"/usr/share/xindy/modules/lang/danish/latin9.xdy"
%dir "/usr/share/xindy/modules/lang/dutch/"
"/usr/share/xindy/modules/lang/dutch/ij-as-ij-utf8-test.xdy"
"/usr/share/xindy/modules/lang/dutch/ij-as-ij-utf8.xdy"
"/usr/share/xindy/modules/lang/dutch/ij-as-y-utf8-test.xdy"
"/usr/share/xindy/modules/lang/dutch/ij-as-y-utf8.xdy"
"/usr/share/xindy/modules/lang/dutch/ij-as-ij-latin1-test.xdy"
"/usr/share/xindy/modules/lang/dutch/ij-as-ij-latin1.xdy"
"/usr/share/xindy/modules/lang/dutch/latin1.xdy"
"/usr/share/xindy/modules/lang/dutch/latin1-test.xdy"
"/usr/share/xindy/modules/lang/dutch/tex-latin1.xdy"
%dir "/usr/share/xindy/modules/lang/english/"
"/usr/share/xindy/modules/lang/english/utf8-test.xdy"
"/usr/share/xindy/modules/lang/english/utf8.xdy"
"/usr/share/xindy/modules/lang/english/ascii.xdy"
"/usr/share/xindy/modules/lang/english/ascii-test.xdy"
"/usr/share/xindy/modules/lang/english/cp1252-test.xdy"
"/usr/share/xindy/modules/lang/english/cp1252.xdy"
"/usr/share/xindy/modules/lang/english/latin9-test.xdy"
"/usr/share/xindy/modules/lang/english/latin9.xdy"
"/usr/share/xindy/modules/lang/english/tex-ascii.xdy"
%dir "/usr/share/xindy/modules/lang/esperanto/"
"/usr/share/xindy/modules/lang/esperanto/utf8-test.xdy"
"/usr/share/xindy/modules/lang/esperanto/utf8.xdy"
"/usr/share/xindy/modules/lang/esperanto/latin3-test.xdy"
"/usr/share/xindy/modules/lang/esperanto/latin3.xdy"
%dir "/usr/share/xindy/modules/lang/estonian/"
"/usr/share/xindy/modules/lang/estonian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/estonian/utf8.xdy"
"/usr/share/xindy/modules/lang/estonian/cp1252-test.xdy"
"/usr/share/xindy/modules/lang/estonian/cp1252.xdy"
"/usr/share/xindy/modules/lang/estonian/latin9-test.xdy"
"/usr/share/xindy/modules/lang/estonian/latin9.xdy"
%dir "/usr/share/xindy/modules/lang/finnish/"
"/usr/share/xindy/modules/lang/finnish/utf8-test.xdy"
"/usr/share/xindy/modules/lang/finnish/utf8.xdy"
"/usr/share/xindy/modules/lang/finnish/cp1252-test.xdy"
"/usr/share/xindy/modules/lang/finnish/cp1252.xdy"
"/usr/share/xindy/modules/lang/finnish/latin9-test.xdy"
"/usr/share/xindy/modules/lang/finnish/latin9.xdy"
"/usr/share/xindy/modules/lang/finnish/tex-cp1252.xdy"
"/usr/share/xindy/modules/lang/finnish/tex-latin9.xdy"
%dir "/usr/share/xindy/modules/lang/french/"
"/usr/share/xindy/modules/lang/french/utf8-test.xdy"
"/usr/share/xindy/modules/lang/french/utf8.xdy"
"/usr/share/xindy/modules/lang/french/cp1252-test.xdy"
"/usr/share/xindy/modules/lang/french/cp1252.xdy"
"/usr/share/xindy/modules/lang/french/latin9-test.xdy"
"/usr/share/xindy/modules/lang/french/latin9.xdy"
%dir "/usr/share/xindy/modules/lang/general/"
"/usr/share/xindy/modules/lang/general/utf8-test.xdy"
"/usr/share/xindy/modules/lang/general/utf8.xdy"
"/usr/share/xindy/modules/lang/general/cp1252-test.xdy"
"/usr/share/xindy/modules/lang/general/cp1252.xdy"
"/usr/share/xindy/modules/lang/general/cp850-test.xdy"
"/usr/share/xindy/modules/lang/general/cp850.xdy"
"/usr/share/xindy/modules/lang/general/latin1-test.xdy"
"/usr/share/xindy/modules/lang/general/latin1.xdy"
"/usr/share/xindy/modules/lang/general/latin9-test.xdy"
"/usr/share/xindy/modules/lang/general/latin9.xdy"
%dir "/usr/share/xindy/modules/lang/georgian/"
"/usr/share/xindy/modules/lang/georgian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/georgian/utf8.xdy"
%dir "/usr/share/xindy/modules/lang/german/"
"/usr/share/xindy/modules/lang/german/din5007-utf8-test.xdy"
"/usr/share/xindy/modules/lang/german/din5007-utf8.xdy"
"/usr/share/xindy/modules/lang/german/duden-utf8-test.xdy"
"/usr/share/xindy/modules/lang/german/duden-utf8.xdy"
"/usr/share/xindy/modules/lang/german/braille-utf8-test.xdy"
"/usr/share/xindy/modules/lang/german/braille-utf8.xdy"
"/usr/share/xindy/modules/lang/german/din5007-latin1-test.xdy"
"/usr/share/xindy/modules/lang/german/din5007-latin1.xdy"
"/usr/share/xindy/modules/lang/german/duden-latin1-test.xdy"
"/usr/share/xindy/modules/lang/german/duden-latin1.xdy"
"/usr/share/xindy/modules/lang/german/tex-din5007-latin1.xdy"
"/usr/share/xindy/modules/lang/german/tex-duden-latin1.xdy"
"/usr/share/xindy/modules/lang/german/tex-latin1.xdy"
%dir "/usr/share/xindy/modules/lang/greek/"
"/usr/share/xindy/modules/lang/greek/translit-utf8-test.xdy"
"/usr/share/xindy/modules/lang/greek/translit-utf8.xdy"
"/usr/share/xindy/modules/lang/greek/utf8-test.xdy"
"/usr/share/xindy/modules/lang/greek/utf8.xdy"
"/usr/share/xindy/modules/lang/greek/polytonic-utf8-test.xdy"
"/usr/share/xindy/modules/lang/greek/polytonic-utf8.xdy"
"/usr/share/xindy/modules/lang/greek/iso88597-test.xdy"
"/usr/share/xindy/modules/lang/greek/iso88597.xdy"
"/usr/share/xindy/modules/lang/greek/translit-latin4-test.xdy"
"/usr/share/xindy/modules/lang/greek/translit-latin4.xdy"
"/usr/share/xindy/modules/lang/greek/translit-tex-test.xdy"
"/usr/share/xindy/modules/lang/greek/translit-tex.xdy"
%dir "/usr/share/xindy/modules/lang/gypsy/"
"/usr/share/xindy/modules/lang/gypsy/northrussian-utf8-test.xdy"
"/usr/share/xindy/modules/lang/gypsy/northrussian-utf8.xdy"
%dir "/usr/share/xindy/modules/lang/hausa/"
"/usr/share/xindy/modules/lang/hausa/utf8-test.xdy"
"/usr/share/xindy/modules/lang/hausa/utf8.xdy"
%dir "/usr/share/xindy/modules/lang/hebrew/"
"/usr/share/xindy/modules/lang/hebrew/utf8-test.xdy"
"/usr/share/xindy/modules/lang/hebrew/utf8.xdy"
"/usr/share/xindy/modules/lang/hebrew/iso88598-test.xdy"
"/usr/share/xindy/modules/lang/hebrew/iso88598.xdy"
%dir "/usr/share/xindy/modules/lang/hungarian/"
"/usr/share/xindy/modules/lang/hungarian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/hungarian/utf8.xdy"
"/usr/share/xindy/modules/lang/hungarian/cp1250-test.xdy"
"/usr/share/xindy/modules/lang/hungarian/cp1250.xdy"
"/usr/share/xindy/modules/lang/hungarian/latin2-test.xdy"
"/usr/share/xindy/modules/lang/hungarian/latin2.xdy"
%dir "/usr/share/xindy/modules/lang/icelandic/"
"/usr/share/xindy/modules/lang/icelandic/utf8-test.xdy"
"/usr/share/xindy/modules/lang/icelandic/utf8.xdy"
"/usr/share/xindy/modules/lang/icelandic/cp1252-test.xdy"
"/usr/share/xindy/modules/lang/icelandic/cp1252.xdy"
"/usr/share/xindy/modules/lang/icelandic/latin1-test.xdy"
"/usr/share/xindy/modules/lang/icelandic/latin1.xdy"
"/usr/share/xindy/modules/lang/icelandic/latin9-test.xdy"
"/usr/share/xindy/modules/lang/icelandic/latin9.xdy"
%dir "/usr/share/xindy/modules/lang/italian/"
"/usr/share/xindy/modules/lang/italian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/italian/utf8.xdy"
"/usr/share/xindy/modules/lang/italian/latin1-test.xdy"
"/usr/share/xindy/modules/lang/italian/latin1.xdy"
%dir "/usr/share/xindy/modules/lang/klingon/"
"/usr/share/xindy/modules/lang/klingon/utf8-test.xdy"
"/usr/share/xindy/modules/lang/klingon/utf8.xdy"
%dir "/usr/share/xindy/modules/lang/kurdish/"
"/usr/share/xindy/modules/lang/kurdish/bedirxan-utf8-test.xdy"
"/usr/share/xindy/modules/lang/kurdish/bedirxan-utf8.xdy"
"/usr/share/xindy/modules/lang/kurdish/turkish-i-utf8-test.xdy"
"/usr/share/xindy/modules/lang/kurdish/turkish-i-utf8.xdy"
"/usr/share/xindy/modules/lang/kurdish/bedirxan-latin5-test.xdy"
"/usr/share/xindy/modules/lang/kurdish/bedirxan-latin5.xdy"
"/usr/share/xindy/modules/lang/kurdish/latin5-test.xdy"
"/usr/share/xindy/modules/lang/kurdish/latin5.xdy"
"/usr/share/xindy/modules/lang/kurdish/turkish-i-latin5-test.xdy"
"/usr/share/xindy/modules/lang/kurdish/turkish-i-latin5.xdy"
%dir "/usr/share/xindy/modules/lang/latin/"
"/usr/share/xindy/modules/lang/latin/utf8-test.xdy"
"/usr/share/xindy/modules/lang/latin/utf8.xdy"
%dir "/usr/share/xindy/modules/lang/latvian/"
"/usr/share/xindy/modules/lang/latvian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/latvian/utf8.xdy"
"/usr/share/xindy/modules/lang/latvian/latin4-test.xdy"
"/usr/share/xindy/modules/lang/latvian/latin4.xdy"
%dir "/usr/share/xindy/modules/lang/lithuanian/"
"/usr/share/xindy/modules/lang/lithuanian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/lithuanian/utf8.xdy"
"/usr/share/xindy/modules/lang/lithuanian/latin4-test.xdy"
"/usr/share/xindy/modules/lang/lithuanian/latin4.xdy"
%dir "/usr/share/xindy/modules/lang/lower-sorbian/"
"/usr/share/xindy/modules/lang/lower-sorbian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/lower-sorbian/utf8.xdy"
"/usr/share/xindy/modules/lang/lower-sorbian/cp1250-test.xdy"
"/usr/share/xindy/modules/lang/lower-sorbian/cp1250.xdy"
"/usr/share/xindy/modules/lang/lower-sorbian/latin2-test.xdy"
"/usr/share/xindy/modules/lang/lower-sorbian/latin2.xdy"
%dir "/usr/share/xindy/modules/lang/macedonian/"
"/usr/share/xindy/modules/lang/macedonian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/macedonian/utf8.xdy"
"/usr/share/xindy/modules/lang/macedonian/cp1251-test.xdy"
"/usr/share/xindy/modules/lang/macedonian/cp1251.xdy"
"/usr/share/xindy/modules/lang/macedonian/iso88595-test.xdy"
"/usr/share/xindy/modules/lang/macedonian/iso88595.xdy"
"/usr/share/xindy/modules/lang/macedonian/isoir111-test.xdy"
"/usr/share/xindy/modules/lang/macedonian/isoir111.xdy"
%dir "/usr/share/xindy/modules/lang/mongolian/"
"/usr/share/xindy/modules/lang/mongolian/cyrillic-utf8-test.xdy"
"/usr/share/xindy/modules/lang/mongolian/cyrillic-utf8.xdy"
%dir "/usr/share/xindy/modules/lang/norwegian/"
"/usr/share/xindy/modules/lang/norwegian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/norwegian/utf8.xdy"
"/usr/share/xindy/modules/lang/norwegian/latin1-test.xdy"
"/usr/share/xindy/modules/lang/norwegian/latin1.xdy"
%dir "/usr/share/xindy/modules/lang/polish/"
"/usr/share/xindy/modules/lang/polish/utf8-test.xdy"
"/usr/share/xindy/modules/lang/polish/utf8.xdy"
"/usr/share/xindy/modules/lang/polish/cp1250-test.xdy"
"/usr/share/xindy/modules/lang/polish/cp1250.xdy"
"/usr/share/xindy/modules/lang/polish/latin2-test.xdy"
"/usr/share/xindy/modules/lang/polish/latin2.xdy"
%dir "/usr/share/xindy/modules/lang/portuguese/"
"/usr/share/xindy/modules/lang/portuguese/utf8-test.xdy"
"/usr/share/xindy/modules/lang/portuguese/utf8.xdy"
"/usr/share/xindy/modules/lang/portuguese/latin1-test.xdy"
"/usr/share/xindy/modules/lang/portuguese/latin1.xdy"
%dir "/usr/share/xindy/modules/lang/romanian/"
"/usr/share/xindy/modules/lang/romanian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/romanian/utf8.xdy"
"/usr/share/xindy/modules/lang/romanian/latin2-test.xdy"
"/usr/share/xindy/modules/lang/romanian/latin2.xdy"
%dir "/usr/share/xindy/modules/lang/russian/"
"/usr/share/xindy/modules/lang/russian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/russian/utf8.xdy"
"/usr/share/xindy/modules/lang/russian/translit-iso-utf8-test.xdy"
"/usr/share/xindy/modules/lang/russian/translit-iso-utf8.xdy"
"/usr/share/xindy/modules/lang/russian/cp1251-test.xdy"
"/usr/share/xindy/modules/lang/russian/cp1251.xdy"
"/usr/share/xindy/modules/lang/russian/iso88595-test.xdy"
"/usr/share/xindy/modules/lang/russian/iso88595.xdy"
"/usr/share/xindy/modules/lang/russian/koi8-r-test.xdy"
"/usr/share/xindy/modules/lang/russian/koi8-r.xdy"
"/usr/share/xindy/modules/lang/russian/translit-iso-tex-test.xdy"
"/usr/share/xindy/modules/lang/russian/translit-iso-tex.xdy"
"/usr/share/xindy/modules/lang/russian/translit-tex.xdy"
"/usr/share/xindy/modules/lang/russian/translit-tgl-tex.xdy"
%dir "/usr/share/xindy/modules/lang/serbian/"
"/usr/share/xindy/modules/lang/serbian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/serbian/utf8.xdy"
"/usr/share/xindy/modules/lang/serbian/cp1251-test.xdy"
"/usr/share/xindy/modules/lang/serbian/cp1251.xdy"
"/usr/share/xindy/modules/lang/serbian/iso88595-test.xdy"
"/usr/share/xindy/modules/lang/serbian/iso88595.xdy"
"/usr/share/xindy/modules/lang/serbian/isoir111-test.xdy"
"/usr/share/xindy/modules/lang/serbian/isoir111.xdy"
%dir "/usr/share/xindy/modules/lang/slovak/"
"/usr/share/xindy/modules/lang/slovak/small-utf8-test.xdy"
"/usr/share/xindy/modules/lang/slovak/small-utf8.xdy"
"/usr/share/xindy/modules/lang/slovak/large-utf8-test.xdy"
"/usr/share/xindy/modules/lang/slovak/large-utf8.xdy"
"/usr/share/xindy/modules/lang/slovak/large-cp1250-test.xdy"
"/usr/share/xindy/modules/lang/slovak/large-cp1250.xdy"
"/usr/share/xindy/modules/lang/slovak/large-latin2-test.xdy"
"/usr/share/xindy/modules/lang/slovak/large-latin2.xdy"
"/usr/share/xindy/modules/lang/slovak/small-cp1250-test.xdy"
"/usr/share/xindy/modules/lang/slovak/small-cp1250.xdy"
"/usr/share/xindy/modules/lang/slovak/small-latin2-test.xdy"
"/usr/share/xindy/modules/lang/slovak/small-latin2.xdy"
%dir "/usr/share/xindy/modules/lang/slovenian/"
"/usr/share/xindy/modules/lang/slovenian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/slovenian/utf8.xdy"
"/usr/share/xindy/modules/lang/slovenian/cp1250-test.xdy"
"/usr/share/xindy/modules/lang/slovenian/cp1250.xdy"
"/usr/share/xindy/modules/lang/slovenian/latin2-test.xdy"
"/usr/share/xindy/modules/lang/slovenian/latin2.xdy"
%dir "/usr/share/xindy/modules/lang/spanish/"
"/usr/share/xindy/modules/lang/spanish/modern-utf8-test.xdy"
"/usr/share/xindy/modules/lang/spanish/modern-utf8.xdy"
"/usr/share/xindy/modules/lang/spanish/traditional-utf8-test.xdy"
"/usr/share/xindy/modules/lang/spanish/traditional-utf8.xdy"
"/usr/share/xindy/modules/lang/spanish/modern-latin1-test.xdy"
"/usr/share/xindy/modules/lang/spanish/modern-latin1.xdy"
"/usr/share/xindy/modules/lang/spanish/traditional-latin1-test.xdy"
"/usr/share/xindy/modules/lang/spanish/traditional-latin1.xdy"
%dir "/usr/share/xindy/modules/lang/swedish/"
"/usr/share/xindy/modules/lang/swedish/utf8-test.xdy"
"/usr/share/xindy/modules/lang/swedish/utf8.xdy"
"/usr/share/xindy/modules/lang/swedish/cp1252-test.xdy"
"/usr/share/xindy/modules/lang/swedish/cp1252.xdy"
"/usr/share/xindy/modules/lang/swedish/latin1-test.xdy"
"/usr/share/xindy/modules/lang/swedish/latin1.xdy"
"/usr/share/xindy/modules/lang/swedish/latin9-test.xdy"
"/usr/share/xindy/modules/lang/swedish/latin9.xdy"
"/usr/share/xindy/modules/lang/swedish/tex-cp1252.xdy"
"/usr/share/xindy/modules/lang/swedish/tex-latin1.xdy"
"/usr/share/xindy/modules/lang/swedish/tex-latin9.xdy"
%dir "/usr/share/xindy/modules/lang/turkish/"
"/usr/share/xindy/modules/lang/turkish/utf8-test.xdy"
"/usr/share/xindy/modules/lang/turkish/utf8.xdy"
"/usr/share/xindy/modules/lang/turkish/latin3-test.xdy"
"/usr/share/xindy/modules/lang/turkish/latin3.xdy"
"/usr/share/xindy/modules/lang/turkish/latin5-test.xdy"
"/usr/share/xindy/modules/lang/turkish/latin5.xdy"
%dir "/usr/share/xindy/modules/lang/ukrainian/"
"/usr/share/xindy/modules/lang/ukrainian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/ukrainian/utf8.xdy"
"/usr/share/xindy/modules/lang/ukrainian/cp1251-test.xdy"
"/usr/share/xindy/modules/lang/ukrainian/cp1251.xdy"
"/usr/share/xindy/modules/lang/ukrainian/koi8-u-test.xdy"
"/usr/share/xindy/modules/lang/ukrainian/koi8-u.xdy"
%dir "/usr/share/xindy/modules/lang/upper-sorbian/"
"/usr/share/xindy/modules/lang/upper-sorbian/utf8-test.xdy"
"/usr/share/xindy/modules/lang/upper-sorbian/utf8.xdy"
"/usr/share/xindy/modules/lang/upper-sorbian/cp1250-test.xdy"
"/usr/share/xindy/modules/lang/upper-sorbian/cp1250.xdy"
"/usr/share/xindy/modules/lang/upper-sorbian/latin2-test.xdy"
"/usr/share/xindy/modules/lang/upper-sorbian/latin2.xdy"
%dir "/usr/share/xindy/modules/lang/vietnamese/"
"/usr/share/xindy/modules/lang/vietnamese/utf8-test.xdy"
"/usr/share/xindy/modules/lang/vietnamese/utf8.xdy"
%dir "/usr/share/xindy/modules/tex/"
%dir "/usr/share/xindy/modules/tex/inputenc/"
"/usr/share/xindy/modules/tex/inputenc/latin1.xdy"
"/usr/share/xindy/modules/tex/inputenc/latin2.xdy"
"/usr/share/xindy/modules/tex/inputenc/latin3.xdy"
"/usr/share/xindy/modules/tex/inputenc/cp1250.xdy"
"/usr/share/xindy/modules/tex/inputenc/cp1252.xdy"
"/usr/share/xindy/modules/tex/inputenc/cp437.xdy"
"/usr/share/xindy/modules/tex/inputenc/cp850.xdy"
"/usr/share/xindy/modules/tex/inputenc/iso88595.xdy"
"/usr/share/xindy/modules/tex/inputenc/koi8-r.xdy"
"/usr/share/xindy/modules/tex/inputenc/koi8-u.xdy"
"/usr/share/xindy/modules/tex/inputenc/isoir111.xdy"
"/usr/share/xindy/modules/tex/inputenc/cp1251.xdy"
"/usr/share/xindy/modules/tex/inputenc/cp855.xdy"
"/usr/share/xindy/modules/tex/inputenc/cp866.xdy"
%dir "/usr/share/xindy/modules/styles/"
"/usr/share/xindy/modules/styles/makeindex.xdy"
"/usr/share/xindy/modules/styles/vermeer.xdy"
%dir "/usr/bin/"
"/usr/bin/makeindex.sh"
